### ISSUE TITLE
Can you change the way of loading Google fonts? There are problems in China

### ISSUE THREAD

**Issue by zhuhaobam** [unocss/unocss#1292]
Failed to fetch web fonts
FetchError: request to https://fonts.googleapis.com/css2?family=DM+Sans&family=DM+Serif+Display&family=DM+Mono&display=swap failed, reason: 
    at async $fetchRaw2 (file:///D:/VueDoc/vtdd/node_modules/.pnpm/ohmyfetch@0.4.18/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
    at async importUrl (D:\VueDoc\vtdd\node_modules\.pnpm\@unocss+preset-web-fonts@0.42.0\node_modules\@unocss\preset-web-fonts\dist\index.c
    at async Object.getCSS (D:\VueDoc\vtdd\node_modules\.pnpm\@unocss+preset-web-fonts@0.42.0\node_modules\@unocss\preset-web-fonts\dist\ind
    at async D:\VueDoc\vtdd\node_modules\.pnpm\@unocss+core@0.42.0\node_modules\@unocss\core\dist\index.cjs:599:138
    at async Promise.all (index 0)

**Comment by antfu** [comment]
I am happy to integrate more providers, but any good alternatives?
