### ISSUE TITLE
VS Code extension slows down the start-up

### ISSUE THREAD

**Issue by moalamri** [unocss/unocss#1306]
Hi,
Thank you so much for the work you've put in unocss.
Currently the VS Code extension adds 2 seconds delay when the editor is opened or when the extension host is restarted.
Here's the debug log:
```log
INFO UNRESPONSIVE extension host: starting to profile NOW
workbench.desktop.main.js:602 
INFO UNRESPONSIVE extension host: received responsive event and cancelling profiling session

ERR Cannot access '_require2' before initialization: ReferenceError: Cannot access '_require2' before initialization
at C://node_modules/.pnpm/vite@3.0.2/node_modules/vite/dist/node/chunks/dep-1513d487.js:44:47
at jiti2 (c:\\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:5544:15)
at C://node_modules/.pnpm/vite@3.0.2/node_modules/vite/dist/node/index.js:1:3263
at jiti2 (c:\\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:5544:15)
at C:\\node_modules\.pnpm\@sveltejs+vite-plugin-svelte@1.0.1_svelte@3.49.0+vite@3.0.2\node_modules\@sveltejs\vite-plugin-svelte\src\utils\id.ts:4:1
at jiti2 (c:\\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:5544:15)
at c://__unconfig_vite.config.js:5:25
at jiti2 (c:\\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:5544:15)
at loadConfigFile (c:\\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:65144:11)
at Object.load (c:\\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:65080:24)
at loadConfig (c:\\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:65206:18)
at reloadConfig (c:\\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:65231:20)
workbench.desktop.main.js:602
WARN UNRESPONSIVE extension host: 'antfu.unocss' took 90% of 2817.106ms
```
```json
    {   "id": "antfu.unocss", "total": 2543432, "percentage": 90
    },{  "id": "gc", "total": 190508, "percentage": 7
    },{  "id": "program", "total": 702, "percentage": 0
    },{  "id": "self", "total": 74949, "percentage": 3
    },{  "id": "vscode.git", "total": 4772, "percentage": 0
    },{  "id": "vscode.json-language-features", "total": 1707, "percentage": 0
    }
```
I included the cpu profiling, but it's very huge I think the extension made nearly 70k ticks
I removed all unrelated, and shortened strings so it's 13mb now.

Thank you so much.
[exthost-710089.zip](https://github.com/unocss/unocss/files/9151271/exthost-710089.zip)

**Comment by antfu** [comment]
Can you share a minimal project that encounters such issue? I didn't have such experience so I am more wondering what is causing this. Thanks

**Comment by moalamri** [comment]
I only have the extension enabled in a single project, that project belongs to work :(
What can I share to make it easy to debug? maybe the configurations?


`vite.config.js`
```js
import { svelte } from "@sveltejs/vite-plugin-svelte";
import { defineConfig } from 'vite'
import autoPreprocess from 'svelte-preprocess';
import UnoCss from './.unocss.config.js';

export default defineConfig(function ({ mode }) {
  const isProduction = mode === 'production';
  return {
    plugins: [svelte({
      preprocess: autoPreprocess(),
    }),
    UnoCss],
    build: {
      emptyOutDir: true,
      minify: 'esbuild',
    }
  };
})
```
--

`.unocss.config.js`
```js
import { extractorSvelte, presetIcons, presetUno, } from 'unocss'
import UnoCss from 'unocss/vite'

export default UnoCss({
  extractors: [extractorSvelte],
  theme: {
    colors: {
      primary: '#034ABA',
      transparent: 'transparent',
      nord: '#2E3440',
      nord1: '#3B4252',
      nord2: '#434C5E',
      nord3: '#4C566A',
      nord4: '#D8DEE9',
      nord5: '#E5E9F0',
      nord6: '#ECEFF4',
      nord7: '#8FBCBB',
      nord8: '#88C0D0',
      nord9: '#81A1C1',
      nord10: '#5E81AC',
      nord11: '#BF616A',
      nord12: '#D08770',
      nord13: '#EBCB8B',
      nord14: '#A3BE8C',
      nord15: '#B48EAD',
    }
  },
  rules: [
    ['gradient-light', { background: 'linear-gradient(to right, #3c80eb, #044dbf, #0143ac)' }]
  ],
  presets: [
    presetUno(),
    presetIcons({
      extraProperties: {
        'width': '9rem'
      }
    })
  ],
})
```

it could be misconfiguration from my side?

**Comment by antfu** [comment]
Could you create a github repo with the configs and your package.json and lockfile and verify that repo also leads to the performance issue?

**Comment by moalamri** [comment]
I will do when I have time then share it here. You can close this until I ask for reopening, currently I have a tight deadline, so I'll make the reproduction soon, 

By the way the CPU profiling has the chain of functions and how many times that function ticked

**Comment by antfu** [comment]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/11247099/180276926-02573b00-5244-4623-a8db-5efa90f06d62.png">
Seems not a valid file

**Comment by moalamri** [comment]
Must be because I tried to short things to make it smaller. 
Btw Notepad.exe can view the file. For me I couldn't even open it in VS Code because it always hang then crash

**Comment by moalamri** [comment]
```log
    at jiti2 (\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:5544:15)
    at loadConfigFile \.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:65144:11)
    at Object.load (\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:65080:24)
    at loadConfig (\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:65206:18)
    at reloadConfig (\.vscode\extensions\antfu.unocss-0.44.5\dist\index.js:65231:20)
```
Can be found here
[// CommonJS proxy to bypass jiti transforms from nuxt 2 and using native ESM](https://github.com/unocss/unocss/blob/e5b29cae6bbf5648e71306dd9fee4cf6324a4a18/packages/nuxt/index.cjs#L1)

**Comment by moalamri** [comment]
Seems to be good in version 0.45.5
