### ISSUE TITLE
unocss-runtime build error

### ISSUE THREAD

**Issue by EvanMeek** [unocss/unocss#1472]
最小实现:
基于 https://github.com/antfu/vitesse 模板，添加unocss-runtime支持。
```shell
npm i -D @unocss-runtime
```
在main.ts中加入如下代码：
```typescript
import { ViteSSG } from "vite-ssg";
import { setupLayouts } from "virtual:generated-layouts";
import App from "./App.vue";
import type { UserModule } from "./types";
import generatedRoutes from "~pages";

import {
  presetAttributify,
  presetIcons,
  presetUno,
  presetWebFonts,
} from "unocss";
import initUnocssRuntime from "@unocss/runtime";

import "@unocss/reset/tailwind.css";
import "./styles/main.css";
import "uno.css";

const routes = setupLayouts(generatedRoutes);

// https://github.com/antfu/vite-ssg
export const createApp = ViteSSG(
  App,
  { routes, base: import.meta.env.BASE_URL },
  (ctx) => {
    // install all modules under `modules/`
    Object.values(
      import.meta.glob<{ install: UserModule }>("./modules/*.ts", {
        eager: true,
      })
    ).forEach((i) => i.install?.(ctx));
  }
);

initUnocssRuntime({
  defaults: {
    presets: [presetUno()],
  },
});
```
可以看到我这边指定了一个 **presetUno()** 预设，随后使用命令进行打包

```shell
vite build
```
得到如下错误：

```shell
➜  vitesse git:(main) ✗ vite build
vite v3.0.0 building for production...
✓ 370 modules transformed.
[vite-plugin-pwa:build] 'fileURLToPath' is not exported by __vite-browser-external, imported by node_modules/.pnpm/local-pkg@0.4.2/node_modules/local-pkg/dist/shared.mjs
file: /home/evan/Demo/vitesse/node_modules/.pnpm/local-pkg@0.4.2/node_modules/local-pkg/dist/shared.mjs:41:9
39: import path from "path";
40: import fs, { promises as fsPromises } from "fs";
41: import { fileURLToPath } from "url";
             ^
42:
43: // node_modules/.pnpm/yocto-queue@1.0.0/node_modules/yocto-queue/index.js
error during build:
Error: 'fileURLToPath' is not exported by __vite-browser-external, imported by node_modules/.pnpm/local-pkg@0.4.2/node_modules/local-pkg/dist/shared.mjs
    at error (file:///usr/lib/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///usr/lib/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12411:16)
    at Module.traceVariable (file:///usr/lib/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:12770:29)
    at ModuleScope.findVariable (file:///usr/lib/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:11422:39)
    at ReturnValueScope.findVariable (file:///usr/lib/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:6355:38)
    at Identifier.bind (file:///usr/lib/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:7422:40)
    at CallExpression.bind (file:///usr/lib/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
    at CallExpression.bind (file:///usr/lib/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:8918:15)
    at ConditionalExpression.bind (file:///usr/lib/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
    at ArrowFunctionExpression.bind (file:///usr/lib/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:5252:23)
```
# 额外说明
**注意: 这边不加任何预设是能编译通过的**

**Comment by antfu** [comment]
Use `import presetIcons from '@unocss/preset-icons/browser'` for `presetIcons`

https://github.com/unocss/unocss/tree/main/packages/preset-icons#browser

**Comment by EvanMeek** [comment]
> 

presetIcons have browser compatible, BUT Attributify not do it. so it will occur error when vite build.

**Comment by laterdays** [comment]
```
import presetIcons from '@unocss/preset-icons';
import { presetUno, presetAttributify } from 'unocss';
import initUnocssRuntime from '@unocss/runtime';
import '@unocss/reset/normalize.css';
import 'uno.css';
import { icons } from '@/assets/icons';

initUnocssRuntime({
  defaults: {
    safelist: [...icons, 'w-min!'],
    rules: [

    ],
    theme: {
      colors: {
       
      }
    },
    presets: [
      presetUno({}),
      presetAttributify({}),
      presetIcons({
        extraProperties: {
          display: 'inline-block',
          'vertical-align': 'middle'
        }
      })
    ]
  }
});

```


```
✓ 3845 modules transformed.
'fileURLToPath' is not exported by __vite-browser-external, imported by node_modules/local-pkg/dist/shared.mjs
file: unocss/node_modules/local-pkg/dist/shared.mjs:41:9
39: import path from "path";
40: import fs, { promises as fsPromises } from "fs";
41: import { fileURLToPath } from "url";
             ^
42:
43: // node_modules/.pnpm/yocto-queue@1.0.0/node_modules/yocto-queue/index.js
error during build:
Error: 'fileURLToPath' is not exported by __vite-browser-external, imported by node_modules/local-pkg/dist/shared.mjs
    at error (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:1858:30)        
    at Module.error (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:12429:16)    at Module.traceVariable (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at ReturnValueScope.findVariable (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at Identifier.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
    at CallExpression.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at CallExpression.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
    at ConditionalExpression.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at ArrowFunctionExpression.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at VariableDeclarator.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at VariableDeclaration.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
    at Program.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5265:73) 
    at Module.bindReferences (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:12425:18)
    at Graph.sortModules (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:23062:20)
    at Graph.build (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:22940:14) 
    at async file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:23730:13
    at async catchUnfinishedHookActions (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:23126:20)
    at async rollupInternal (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:23727:5)
    at async doBuild (file:///unocss/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45399:24)
    at async build (file:///unocss/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45237:16)
    at async CAC.<anonymous> (file:///unocss/node_modules/vite/dist/node/cli.js:756:9)    
ERROR: "build-only" exited with 1.
```

if presets are empty  build is successful 


@antfu  @EvanMeek  

How should I resolve this error, currently unable to pack
