### ISSUE TITLE
Variant Group error with arbitrary pseudo-elements

### ISSUE THREAD

**Issue by itpropro** [unocss/unocss#1485]
When using more than one arbitrary pseudo-element like `[&::-webkit-slider-thumb]:(appearance-none bg-white)`, the `transformerVariantGroup` transformer crashes with the following error:

```
1:16:40 PM [vite] Internal server error: Invalid string length
  Plugin: unocss:transformers:pre
  File: X:/repo/src/components/Component.vue
      at Array.join (<anonymous>)
      at X:\repo\node_modules\.pnpm\@unocss+core@0.45.9\node_modules\@unocss\core\dist\index.cjs:238:123
      at String.replace (<anonymous>)
      at Object.expandVariantGroup (X:\repo\node_modules\.pnpm\@unocss+core@0.45.9\node_modules\@unocss\core\dist\index.cjs:233:23)
      at Object.transform (X:\repo\node_modules\.pnpm\@unocss+transformer-variant-group@0.45.9\node_modules\@unocss\transformer-variant-group\dist\index.cjs:10:12)
      at applyTransformers (file:///X:\repo/node_modules/.pnpm/@unocss+vite@0.45.9_vite@3.0.9/node_modules/@unocss/vite/dist/index.mjs:821:13)
      at TransformContext.transform (file:///X:/repo/node_modules/.pnpm/@unocss+vite@0.45.9_vite@3.0.9/node_modules/@unocss/vite/dist/index.mjs:843:14)
      at Object.transform (file:///X:/repo/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:35579:53)
      at loadAndTransform (file:///X:/repo/node_modules/.pnpm/vite@3.0.9/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:39888:51)
```

Reproduction (**be careful, the playground will crash, as soon as you set the `Transformer` checkbox**): 
https://uno.antfu.me/play/?html=DwEwlgbgUAkABHAxgGwIYGd0F4BEAnAUzQBdIC4AzZAgDzgFswA7AWgAsX1FCCnLqaLRAHtkcAOaoADiwAccAFYBXdKQoBPIb2IE8cYRF1VhAd3ZgQIXnABG4luLypNsgAyu4UwQEYAbHHR6AC4pTW8AJhxYAD5YBGBmKSViOIQkNExcaSkCVCcmRAIWJmEmcmFk5GYikrLbe2J89Ck87TgAbQAyIKCWEwIbAGswYk4qqzwWYjYlehsAXSCACmzc-MLi0vI7PrYR8g4-ODMAFgBKDu7e-qGRsYtdFjwlJiZUG2opp0RBxaWdxwEawcE7HFgUJTIZBnKLwNLEdQ5XD5cQEWEIAD0sRgwAx4Ag2KAA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAgjDFMAEYCuMwWAnpVQ16jAJIBjYnSHVaDGAFVcEWWwCGuOlmggMUAGrr2mmAHEoELmEoBfOFksg4Aci4qJdOi6RIMAD0hYdGx1LgAbeEwcfCISYFIACmRUKAj6AC44AG0qVGyXCS46GAgQAFo08IwXckQ4KXDoLJdaNBc4WwBdKi7ZOgALaBgimDoslNRXIpKy8sHh0ZcWmACYcvDSOFX-dehNUgw4IYA3fQyd9dX1cJ9UW1kRBXGcvLlRJRVEgEpZYXlGCw2JweHx%2BD8-u8FJJpMk3qg6BIbhgsgBGAB0ACZIagJGhcC0BqwwOMAPSk%2BggdGDUl3Ka2X69NRQTTaXT6F65VAASA0Wh0UD0hmMwFMFisYAhvSQDKQQA&options=N4XyA

**Comment by itpropro** [comment]
It still crashes with this code, any idea what the reason could be?

**Comment by itpropro** [comment]
The reproduction still works. As soon as you check the `Transform` checkbox, unocss crashes the whole website.

**Comment by Akryum** [comment]
Still have the issue with 0.49.6
![image](https://user-images.githubusercontent.com/2798204/219529042-4114bb85-24f5-4518-bae1-51c10d5557f2.png)

**Comment by sibbng** [comment]
@Akryum That is definitely a separate issue. Be sure you are installed [transformer-variant-group](https://github.com/unocss/unocss/tree/main/packages/transformer-variant-group) in your project. If the issue still continues please create an issue with reproduction.

**Comment by Akryum** [comment]
> @Akryum That is definitely a separate issue. Be sure you are installed [transformer-variant-group](https://github.com/unocss/unocss/tree/main/packages/transformer-variant-group) in your project. If the issue still continues please create an issue with reproduction.

Oh ok, sorry for the noise
