### ISSUE TITLE
I can't do component test with Cypress

### ISSUE THREAD

**Issue by bernardo-zuchowski** [unocss/unocss#1628]
### Current behavior

First, I can't run test:component.

I update Cypress to 10.8.0 (latest version), then I remove the cypress folder and cypress.config.ts so I can do the initial configuration of component test.

When I try to mount the first component with Cypress mount, this error appears:
![image](https://user-images.githubusercontent.com/87351323/191603467-957410ae-5a17-48e0-a332-a0fc1395b890.png)

### Desired behavior

I want to mount the component and test them, with the Vitesse settings and with the Cypress tools.

### Test code to reproduce

https://github.com/bernardo-zuchowski/vitesse-cypress-issue

### Cypress Version

10.8.1

### Node version

16.17.0

### Operating System

Linux 5.15 Manjaro Linux

### Debug Logs

```shell
Error: Cannot overwrite a zero-length range – use appendLeft or prependRight instead
    at MagicString.overwrite (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/magic-string@0.26.2/node_modules/magic-string/src/MagicString.js:344:10)
    at Object.expandVariantGroup (/home/bernardo/Documentos/vitesse/node_modules/.pnpm/@unocss+core@0.45.5/node_modules/@unocss/core/dist/index.cjs:246:16)
    at Object.transform (/home/bernardo/Documentos/vitesse/node_modules/.pnpm/@unocss+transformer-variant-group@0.45.5/node_modules/@unocss/transformer-variant-group/dist/index.cjs:10:12)
    at applyTransformers (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/@unocss+vite@0.45.5_vite@3.0.4/node_modules/@unocss/vite/dist/index.mjs:815:13)
    at transform (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/@unocss+vite@0.45.5_vite@3.0.4/node_modules/@unocss/vite/dist/index.mjs:842:16)
    at applyHtmlTransforms (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:41563:27)
    at Object.transformIndexHtml (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:57480:16)
    at /home/bernardo/.cache/Cypress/10.8.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/vite-dev-server/dist/plugins/cypress.js:66:57
    at call (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:46058:7)
    at next (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:46002:5)
    at Function.handle (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:46005:3)
    at Server.app (file:///home/bernardo/Documentos/vitesse/node_modules/.pnpm/vite@3.0.4/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:45870:37)
    at Server.emit (node:events:513:28)
    at Server.emit (node:domain:489:12)
    at parserOnIncoming (node:_http_server:980:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

**Comment by bernardo-zuchowski** [comment]
https://github.com/cypress-io/cypress/issues/23923

**Comment by Flower-F** [comment]
It's the problem of the `transformerVariantGroup` plugin, you can comment out this plugin in the `uno.config.ts` file and everything will work well. There might be some bugs of this plugin, but I think it doesn't influence the use of unocss, as the `presetAttributify` preset works better than it and can fully replace it.

**Comment by antfu** [comment]
Can you check with the latest UnoCSS? I remember this has been fixed

**Comment by Flower-F** [comment]
I tried it with the latest version of UnoCSS, and everything works well. So I think this issue could be closed now. @bernardo-zuchowski
