### ISSUE TITLE
VSCode remote ssh activating extension antfu.unocss failed

### ISSUE THREAD

**Issue by Garfield550** [unocss/unocss#1662]
Downgrade to v0.45.23 works fine.

VSCode: 1.71.2 (Universal)
UnoCSS Extension: v0.45.25

```
[2022-09-29 04:07:21.458] [exthost] [info] ExtensionService#_doActivateExtension antfu.unocss, startup: true, activationEvent: 'workspaceContains:**/vite.config.*,**/nuxt.config.*,**/astro.config.*,**/iles.config.*,**/svelte.config.*,**/uno.config.*,**/unocss.config.*,**/package.json'
[2022-09-29 04:07:21.762] [exthost] [error] Activating extension antfu.unocss failed due to an error:
[2022-09-29 04:07:21.762] [exthost] [error] TypeError: The "path" argument must be of type string or an instance of URL. Received undefined
	at new NodeError (node:internal/errors:371:5)
	at fileURLToPath (node:internal/url:1417:11)
	at ../../node_modules/.pnpm/vite@3.1.2_terser@5.15.0/node_modules/vite/dist/node/constants.js (/home/garfield/.vscode-server/extensions/antfu.unocss-0.45.25/dist/index.js:63311:41)
	at __init (/home/garfield/.vscode-server/extensions/antfu.unocss-0.45.25/dist/index.js:9:56)
	at ../../node_modules/.pnpm/vite@3.1.2_terser@5.15.0/node_modules/vite/dist/node/chunks/dep-cff57044.js (/home/garfield/.vscode-server/extensions/antfu.unocss-0.45.25/dist/index.js:132860:5)
	at __init (/home/garfield/.vscode-server/extensions/antfu.unocss-0.45.25/dist/index.js:9:56)
	at Object.<anonymous> (/home/garfield/.vscode-server/extensions/antfu.unocss-0.45.25/dist/index.js:177052:1)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.s._load (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:111:14538)
	at Function.p._load (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:106:62866)
	at Function.E._load (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:106:62234)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/loader.js:5:101)
	at b._loadCommonJSModule (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:106:64346)
	at b._doActivateExtension (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:97:14941)
	at b._activateExtension (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:97:13880)
	at Object.actualActivateExtension (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:97:9877)
	at E._activate (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:8241)
	at E._waitForDepsThenActivate (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:8177)
	at E._initialize (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:7541)
	at new E (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:7340)
	at P._createAndSaveOperation (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:6965)
	at P._handleActivationRequest (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:6876)
	at /home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:5308
	at Array.map (<anonymous>)
	at P._activateExtensions (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:5296)
	at P.activateById (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:85:5172)
	at b._activateById (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:97:11926)
	at b._handleWorkspaceContainsEagerExtension (/home/garfield/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/out/vs/workbench/api/node/extensionHostProcess.js:97:19467)
	at async Promise.all (index 25)
	at async Promise.all (index 1)

```

**Comment by Garfield550** [comment]
#1652 #1654
