### ISSUE TITLE
VSCode Extension: Failing to find config

### ISSUE THREAD

**Issue by MMMikeM** [unocss/unocss#1873]
Hi friends. Thanks for all the work on this project so far.

I'm having some trouble with the VS Code extension and am hoping you can point me in the correct direction to troubleshoot from here.

Am I perhaps looking for the _wrong_ config?

<details>
   <summary>Error from Remote Extension Log</summary>

```
2022-11-12 11:36:51.740 [error] /home/mike/Development/solidstart/node_modules/.pnpm/vitefu@0.1.1_vite@3.2.3/node_modules/vitefu/src/index.js:8
    const { createRequire } = (await Promise.resolve().then(() => require('module'))).default;
                                     ^^^^^^^

SyntaxError: Unexpected identifier
	at new Script (node:vm:100:7)
	at createScript (node:vm:257:10)
	at Object.runInThisContext (node:vm:305:10)
	at jiti2 (/home/mike/.vscode-server/extensions/antfu.unocss-0.45.21/dist/index.js:3613:48)
	at /home/mike/Development/solidstart/node_modules/.pnpm/vite-plugin-solid@2.4.0_solid-js@1.6.2+vite@3.2.3/node_modules/vite-plugin-solid/dist/esm/index.mjs:8:15
	at jiti2 (/home/mike/.vscode-server/extensions/antfu.unocss-0.45.21/dist/index.js:3618:15)
	at /home/mike/Development/solidstart/node_modules/.pnpm/solid-start@0.2.5_3zrnixj5s2zo7r5ma456ac2ypm/node_modules/solid-start/vite/plugin.js:11:47
	at jiti2 (/home/mike/.vscode-server/extensions/antfu.unocss-0.45.21/dist/index.js:3618:15)
	at /home/mike/Development/solidstart/__unconfig_vite.config.ts:5:36
	at jiti2 (/home/mike/.vscode-server/extensions/antfu.unocss-0.45.21/dist/index.js:3618:15)
	at loadConfigFile (/home/mike/.vscode-server/extensions/antfu.unocss-0.45.21/dist/index.js:63449:11)
	at async Object.load (/home/mike/.vscode-server/extensions/antfu.unocss-0.45.21/dist/index.js:63381:24)
	at async loadConfig (/home/mike/.vscode-server/extensions/antfu.unocss-0.45.21/dist/index.js:63511:18)
	at async reloadConfig (/home/mike/.vscode-server/extensions/antfu.unocss-0.45.21/dist/index.js:63537:20)
2022-11-12 11:36:51.774 [error] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/mike/Development/solidstart/__unconfig_vite.config.ts'
    at Function._handleError (/home/mike/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:94:29967)
    at Object.stat (/home/mike/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:94:28335)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-11-12 11:36:51.858 [error] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat '/home/mike/Development/solidstart/__unconfig_vite.config.ts'
    at Function._handleError (/home/mike/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:94:29967)
    at Object.stat (/home/mike/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:94:28335)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    
```
</details>
    
<details>
<summary>vite.config.ts</summary>

```
import solid from "solid-start/vite"
import { defineConfig } from "vite"
import presetUno from "unocss/preset-uno"
import UnoCSS from "unocss/vite"
import presetAttributify from "@unocss/preset-attributify"
import transformerDirectives from "@unocss/transformer-directives"

export default defineConfig({
  plugins: [
    solid(),
    UnoCSS({
      presets: [presetUno(), presetAttributify()],
      transformers: [transformerDirectives()],
    }),
  ],
})
```

Thanks for taking a look! Having a real blast using this so far, outside of the intellisense not working.

**Comment by nexxeln** [comment]
+1, I'm not getting any autocomplete or css properties of the class on hover. Reverting to 0.40.0 of the extension works for now.

**Comment by MMMikeM** [comment]
@nexxeln thanks for the tip!

What's odd, is it _has_ worked intermittently a couple of times, without any changes to config or consistent pattern 🤔

**Comment by OrJDev** [comment]
> +1, I'm not getting any autocomplete or css properties of the class on hover. Reverting to 0.40.0 of the extension works for now.

+1

**Comment by zyyv** [comment]
You can try putting the config into `unocss.config.ts` to make the extension better aware.

**Comment by MMMikeM** [comment]
@zyyv that did the trick!!! Thanks so much.

Is it worth adding this to the documentation anywhere? I'd be happy to assist!

**Comment by zyyv** [comment]
In fact, the unocss extension can load configuration from [the following files](https://github.com/unocss/unocss/blob/main/packages/vscode/README.md#features), it already exists in the documentation.
There are also related issues before, but I think it would be more efficient to use unocss single file configuration.

**Comment by nexxeln** [comment]
> You can try putting the config into `unocss.config.ts` to make the extension better aware.

This worked for me too. But I'm curious why it doesn't work with `vite.config.ts`

**Comment by nexxeln** [comment]
> > You can try putting the config into `unocss.config.ts` to make the extension better aware.
> 
> This worked for me too. But I'm curious why it doesn't work with `vite.config.ts`, it's mentioned in the docs.

**Comment by OrJDev** [comment]
> > You can try putting the config into `unocss.config.ts` to make the extension better aware.
> 
> This worked for me too. But I'm curious why it doesn't work with `vite.config.ts`, it's mentioned in the docs

ye i mean  it does work but it is obv a bug as its mentioned in the docs that uno config is not required (if you use vite, astro etc)

**Comment by johnnypea** [comment]
I can confirm it doesn't work only with `vite.config.ts`. I must have added `unocss.config.ts`, which in my case is empty.

**Comment by louwers** [comment]
Has anyone been able to get it to work with @unocss/nuxt?

**Comment by Techassi** [comment]
@louwers You can manually import the `defineNuxtConfig` helper like this:

```ts
import { defineNuxtConfig } from 'nuxt/config';

export default defineNuxtConfig({
  modules: ['@unocss/nuxt'],
  unocss: {
    preflight: true,
  },
});
```

The extension should now be able to find the config in `nuxt.config.ts`. More information in the [official docs](https://nuxt.com/docs/guide/directory-structure/nuxt.config).

**Comment by prodkt** [comment]
All of a sudden in a project that's worked perfect up until now this is happening. Theres some sort of bug happening here prettier also is flagging bad syntax on all unocss helpers.

**Comment by milkoqq** [comment]
Hey, I just initiated a SvelteKit (ver586) project with Vite and the VSCode extension doesnt work for me too. I swear I used it a couple of months ago with Svelte+Vite and it worked flawlessly. 
I configured just the vite.config.js
`import { sveltekit } from '@sveltejs/kit/vite';
import Unocss from 'unocss/vite'

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [sveltekit(), Unocss({})]
};

export default config;
`
