### ISSUE TITLE
unocss conflicts with functional components

### ISSUE THREAD

**Issue by popdo** [unocss/unocss#1905]
unocss is not compatible with third-party ui component libraries. As long as a functional component is present, an error will be reported and the project will not start properly.

My component code is:

```js
function doneAllTodo(cate) {
  if (!doneCateId.value) {
    Modal.error({
        title: 'hello world!',
        content: ('abcdefg?'),
        okText:'ok',
        hideCancel:false,
        modalClass:'dialog-msg',
        onOk:() => {
            uiCateModal.value = true
        }
    });
    return;
  }
}
```

The following error was reported：

```sh
[vite:vue] [@vue/compiler-sfc] Unexpected token (256:9)

/Users/lee/www/utools/task/src/components/Main.vue
288|          hideCancel:false,
289|          modalClass:'dialog-msg',
290|           => {
   |           ^
291|              uiCateModal.value = true
292|          }
file: /Users/lee/www/utools/task/src/components/Main.vue:256:9
error during build:
SyntaxError: [@vue/compiler-sfc] Unexpected token (256:9)

/Users/lee/www/utools/task/src/components/Main.vue
288|          hideCancel:false,
289|          modalClass:'dialog-msg',
290|           => {
   |           ^
291|              uiCateModal.value = true
292|          }
    at instantiate (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:67:32)
    at constructor (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:364:12)
    at JSXParserMixin.raise (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:3364:19)
    at JSXParserMixin.unexpected (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:3397:16)
    at JSXParserMixin.parsePropertyName (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12202:24)
    at JSXParserMixin.parsePropertyDefinition (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12059:22)
    at JSXParserMixin.parseObjectLike (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11993:21)
    at JSXParserMixin.parseExprAtom (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11464:23)
    at JSXParserMixin.parseExprAtom (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:7238:20)
    at JSXParserMixin.parseExprSubscripts (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11171:23)
    at JSXParserMixin.parseUpdate (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11153:21)
    at JSXParserMixin.parseMaybeUnary (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11127:23)
    at JSXParserMixin.parseMaybeUnaryOrPrivate (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10956:61)
    at JSXParserMixin.parseExprOps (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10962:23)
    at JSXParserMixin.parseMaybeConditional (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10937:23)
    at JSXParserMixin.parseMaybeAssign (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10895:21)
    at /Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10863:39
    at JSXParserMixin.allowInAnd (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12640:12)
    at JSXParserMixin.parseMaybeAssignAllowIn (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10863:17)
    at JSXParserMixin.parseExprListItem (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12380:18)
    at JSXParserMixin.parseCallExpressionArguments (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11367:22)
    at JSXParserMixin.parseCoverCallAndAsyncArrowHead (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11279:29)
    at JSXParserMixin.parseSubscript (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11210:19)
    at JSXParserMixin.parseSubscripts (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11184:19)
    at JSXParserMixin.parseExprSubscripts (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11175:17)
    at JSXParserMixin.parseUpdate (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11153:21)
    at JSXParserMixin.parseMaybeUnary (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:11127:23)
    at JSXParserMixin.parseMaybeUnaryOrPrivate (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10956:61)
    at JSXParserMixin.parseExprOps (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10962:23)
    at JSXParserMixin.parseMaybeConditional (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10937:23)
    at JSXParserMixin.parseMaybeAssign (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10895:21)
    at JSXParserMixin.parseExpressionBase (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10845:23)
    at /Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10840:39
    at JSXParserMixin.allowInAnd (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12635:16)
    at JSXParserMixin.parseExpression (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:10840:17)
    at JSXParserMixin.parseStatementContent (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:13043:23)
    at JSXParserMixin.parseStatement (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12917:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:13497:25)
    at JSXParserMixin.parseBlockBody (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:13489:10)
    at JSXParserMixin.parseBlock (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:13477:10)
    at JSXParserMixin.parseStatementContent (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12993:21)
    at JSXParserMixin.parseStatement (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12917:17)
    at JSXParserMixin.parseIfStatement (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:13281:28)
    at JSXParserMixin.parseStatementContent (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12952:21)
    at JSXParserMixin.parseStatement (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12917:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:13497:25)
    at JSXParserMixin.parseBlockBody (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:13489:10)
    at JSXParserMixin.parseBlock (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:13477:10)
    at JSXParserMixin.parseFunctionBody (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12287:24)
    at JSXParserMixin.parseFunctionBodyAndFinish (/Users/lee/www/utools/task/node_modules/@babel/parser/lib/index.js:12271:10)
```

uninstalling unocss will go back to normal.

**Comment by zyyv** [comment]
I'm having a hard time seeing this as a problem with UnoCSS. From the error message, it has nothing to do with UnoCSS.
