### ISSUE TITLE
unocss runtime build error 

### ISSUE THREAD

**Issue by laterdays** [unocss/unocss#1949]
```
import presetIcons from '@unocss/preset-icons';
import { presetUno, presetAttributify } from 'unocss';
import initUnocssRuntime from '@unocss/runtime';
import '@unocss/reset/normalize.css';
import 'uno.css';
import { icons } from '@/assets/icons';

initUnocssRuntime({
  defaults: {
    safelist: [...icons, 'w-min!'],
    rules: [

    ],
    theme: {
      colors: {
       
      }
    },
    presets: [
      presetUno({}),
      presetAttributify({}),
      presetIcons({
        extraProperties: {
          display: 'inline-block',
          'vertical-align': 'middle'
        }
      })
    ]
  }
});

```

```
✓ 3845 modules transformed.
'fileURLToPath' is not exported by __vite-browser-external, imported by node_modules/local-pkg/dist/shared.mjs
file: unocss/node_modules/local-pkg/dist/shared.mjs:41:9
39: import path from "path";
40: import fs, { promises as fsPromises } from "fs";
41: import { fileURLToPath } from "url";
             ^
42:
43: // node_modules/.pnpm/yocto-queue@1.0.0/node_modules/yocto-queue/index.js
error during build:
Error: 'fileURLToPath' is not exported by __vite-browser-external, imported by node_modules/local-pkg/dist/shared.mjs
    at error (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:1858:30)        
    at Module.error (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:12429:16)    at Module.traceVariable (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at ReturnValueScope.findVariable (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at Identifier.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
    at CallExpression.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at CallExpression.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
    at ConditionalExpression.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at ArrowFunctionExpression.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at VariableDeclarator.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at VariableDeclaration.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
    at Program.bind (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:5265:73) 
    at Module.bindReferences (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:12425:18)
    at Graph.sortModules (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:23062:20)
    at Graph.build (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:22940:14) 
    at async file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:23730:13
    at async catchUnfinishedHookActions (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:23126:20)
    at async rollupInternal (file:///unocss/node_modules/rollup/dist/es/shared/rollup.js:23727:5)
    at async doBuild (file:///unocss/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45399:24)
    at async build (file:///unocss/node_modules/vite/dist/node/chunks/dep-67e7f8ab.js:45237:16)
    at async CAC.<anonymous> (file:///unocss/node_modules/vite/dist/node/cli.js:756:9)    
ERROR: "build-only" exited with 1.
```

if presets are empty  build is successful

**Comment by laterdays** [comment]
```
"dependencies": {
    "@unocss/reset": "^0.47.5",
    "@unocss/runtime": "^0.47.5",
  },
  "devDependencies": {
    "@iconify-json/carbon": "^1.1.11",
    "@unocss/preset-icons": "^0.47.5",
    "@unocss/transformer-variant-group": "^0.47.5",
    "unocss": "^0.47.5",
  },
```

**Comment by laterdays** [comment]
The @unocss/runtime package is used because there is no network in production, but it cannot be built after setting presets

**Comment by fazulk** [comment]
Getting the same issue here 

```59: import process2 from "process";
60: import path from "path";
61: import fs, { promises as fsPromises } from "fs";
                 ^
62: import { fileURLToPath } from "url";
```
with:
```
  "vite": "^3.0.2",
  "unocss": "^0.49.5",
  "@unocss/runtime": "^0.49.5",
