### ISSUE TITLE
astro esm.sh 500 internal server error

### ISSUE THREAD

**Issue by Dragonlord1005** [unocss/unocss#2029]
When using unocss icons with the esm.sh cdn or any cdn, it errors with 500 internal server error

`500 Internal Server Error (https://esm.sh/@iconify-json/material-symbols/icons.json)
 error   500 Internal Server Error (https://esm.sh/@iconify-json/material-symbols/icons.json)
FetchError: 500 Internal Server Error (https://esm.sh/@iconify-json/material-symbols/icons.json)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

thats the error log

**Comment by ruslankonev** [comment]
Confirm this

**Comment by lishaobos** [comment]
hi, you can use https://cdn.skypack.dev/ instead of https://esm.sh

**Comment by Dragonlord1005** [comment]
cdn.skypack.dev also fails, I will test it later this week when I find the time

**Comment by Dragonlord1005** [comment]
Just tested on [codesandbox](https://codesandbox.io/p/github/Dragonlord1005/astro-boi/draft/sweet-brook?file=%2FREADME.mdl), same error

**Comment by yzh990918** [comment]
The same issue too.

**Comment by kamontat** [comment]
I got same error on sveltekit (vite) as well.

**Comment by Dragonlord1005** [comment]
Managed to get a complete error log, at least I think I did

```
node:internal/process/task_queues:96
    runMicrotasks();
    ^

FetchError: 500 Internal Server Error (https://esm.sh/@iconify-json/logos/icons.json)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /workspaces/astro-boi/node_modules/.pnpm/@unocss+preset-icons@0.48.0/node_modules/@unocss/preset-icons/dist/shared/preset-icons.fa2b0f2c.cjs:786:21
    at async /workspaces/astro-boi/node_modules/.pnpm/@unocss+preset-icons@0.48.0/node_modules/@unocss/preset-icons/dist/core.cjs:127:22
    at async rules.layer.layer (/workspaces/astro-boi/node_modules/.pnpm/@unocss+preset-icons@0.48.0/node_modules/@unocss/preset-icons/dist/core.cjs:86:21)
    at async UnoGenerator.parseUtil (file:///workspaces/astro-boi/node_modules/.pnpm/@unocss+core@0.48.0/node_modules/@unocss/core/dist/index.mjs:755:22)
    at async UnoGenerator.parseToken (file:///workspaces/astro-boi/node_modules/.pnpm/@unocss+core@0.48.0/node_modules/@unocss/core/dist/index.mjs:509:120)
    at async /workspaces/astro-boi/node_modules/.pnpm/@unocss+transformer-compile-class@0.48.0/node_modules/@unocss/transformer-compile-class/dist/index.cjs:25:101
    at async Promise.all (index 0)
    at async Object.transform (/workspaces/astro-boi/node_modules/.pnpm/@unocss+transformer-compile-class@0.48.0/node_modules/@unocss/transformer-compile-class/dist/index.cjs:25:26)
    at async applyTransformers (file:///workspaces/astro-boi/node_modules/.pnpm/@unocss+vite@0.48.0/node_modules/@unocss/vite/dist/index.mjs:242:5)
    at async extractFile (file:///workspaces/astro-boi/node_modules/.pnpm/@unocss+vite@0.48.0/node_modules/@unocss/vite/dist/index.mjs:274:28)
    at async Promise.all (index 2)
    at async setupExtraContent (file:///workspaces/astro-boi/node_modules/.pnpm/@unocss+vite@0.48.0/node_modules/@unocss/vite/dist/index.mjs:295:5)
```

**Comment by yzh990918** [comment]
Maybe we need his help 😄  @antfu .

**Comment by Dragonlord1005** [comment]
The issue seems to have gone away on Astro at least...
