### ISSUE TITLE
Nuxt 3 build error with `@unocss/nuxt` in ~0.48.3

### ISSUE THREAD

**Issue by atlanswer** [unocss/unocss#2055]
## Description

Hi, upgrading the `@unocss/nuxt` module from 0.46.5 to ~0.48.3 introduces a build error.

I don't have time to track it down. If you need more information, please let me know.

<details>
<summary>Error log</summary>

```
❯ pnpm build

> package@0.0.2 build ***
> nuxt build

Nuxi 3.0.0 
Nuxt 3.0.0 with Nitro 1.0.0

i Client built in 3786ms
i Building server...

 ERROR  [unocss:global:build:scan] [postcss] ***\server.mjs-unocss-hash.css:1:3544: Double colon


 ERROR  [postcss] ***\server.mjs-unocss-hash.css:1:3544: Double colon

  at Input.error (***\node_modules\.pnpm\postcss@8.4.20\node_modules\postcss\lib\input.js:148:16)
  at Parser.doubleColon (***\node_modules\.pnpm\postcss@8.4.20\node_modules\postcss\lib\parser.js:561:22)
  at Parser.colon (***\node_modules\.pnpm\postcss@8.4.20\node_modules\postcss\lib\parser.js:516:16)
  at Parser.checkMissedSemicolon (***\node_modules\.pnpm\postcss@8.4.20\node_modules\postcss\lib\parser.js:581:22)
  at Parser.decl (***\node_modules\.pnpm\postcss@8.4.20\node_modules\postcss\lib\parser.js:279:12)
  at Parser.other (***\node_modules\.pnpm\postcss@8.4.20\node_modules\postcss\lib\parser.js:128:18)
  at Parser.parse (***\node_modules\.pnpm\postcss@8.4.20\node_modules\postcss\lib\parser.js:72:16)
  at parse (***\node_modules\.pnpm\postcss@8.4.20\node_modules\postcss\lib\parse.js:11:12)
  at new LazyResult (***\node_modules\.pnpm\postcss@8.4.20\node_modules\postcss\lib\lazy-result.js:133:16)
  at Processor.process (***\node_modules\.pnpm\postcss@8.4.20\node_modules\postcss\lib\processor.js:28:14)

***:
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  ***@0.0.2 build: `nuxt build`
Exit status 1
```

</details>

The dev server works as expected.

## Steps to reproduce

Reproduction: https://stackblitz.com/edit/nuxt-3-unocss

Manually run build in the terminal: `pnpm build`.

Possibly related: #1965

### Conditions

1. update `@unocss/nuxt` to ~0.48.3, the exact version is unknown
2. an element with an attribute of `style="display: none"` in an SFC
3. a script block with some content (i.e. non-empty, I just put `//` in there) in the same SFC

If any of the conditions are not met, the error may not occur.

**Comment by YunYouJun** [comment]
I had a similar problem and was looking forward to a solution.

**Comment by yonghui666** [comment]
> ## 描述
> 嗨，将`@unocss/nuxt`模块从 0.46.5 升级到 ~0.48.3 会引入构建错误。
> 
> 我没有时间追查它。如果您需要更多信息，请告诉我。
> 
> 错误记录
> 开发服务器按预期工作。
> 
> ## 重现步骤
> 复制： https: [//stackblitz.com/edit/nuxt-3-unocss](https://stackblitz.com/edit/nuxt-3-unocss)
> 
> 在终端中手动运行构建：`pnpm build`.
> 
> 可能相关：#1965
> 
> ### 状况
> 1. 更新`@unocss/nuxt`到~0.48.3，具体版本未知
> 2. `style="display: none"`SFC 中具有属性的元素
> 3. `//`在同一个 SFC 中包含一些内容（即非空，我只是放在那里）的脚本块
> 
> 如果不满足任何条件，则可能不会发生错误。

请求大佬怎么解决的呀

**Comment by zyyv** [comment]
@yonghui666 如果尝试最新版本还有问题，可以麻烦你重新发一个issue吗，我有空会看一下
