### ISSUE TITLE
Astro: Failed to load url @unocss/reset/tailwind.css

### ISSUE THREAD

**Issue by frenicohansen** [unocss/unocss#2342]
### UnoCSS version

0.50.4

### Describe the bug

Hi,

I just started a new Astro Project using `pnpm create astro@latest`. And then I installed UnoCss exactly as the [guide](https://github.com/unocss/unocss/tree/main/packages/astro).

When trying to start the development server, I got this error instead.

```
Failed to load url @unocss/reset/tailwind.css (resolved id: @unocss/reset/tailwind.css) in astro:scripts/page-ssr.js. Does the file exist?
 error   Cannot find module '@unocss/reset/tailwind.css' imported from 'astro:scripts/page-ssr.js'
  File:
    /project/home/hazelnuss/workspace/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52451:25
  Code:
    52450 |         if (!resolved) {
    > 52451 |             const err = new Error(`Cannot find module '${id}' imported from '${importer}'`);
            |                         ^
      52452 |             err.code = 'ERR_MODULE_NOT_FOUND';
      52453 |             throw err;
      52454 |         }
  Stacktrace:
Error: Cannot find module '@unocss/reset/tailwind.css' imported from 'astro:scripts/page-ssr.js'
    at nodeImport (file:///project/home/hazelnuss/workspace/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52451:25)
    at ssrImport (file:///project/home/hazelnuss/workspace/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52374:20)
    at eval (astro:scripts/page-ssr.js:3:50)
    at instantiateModule (file:///project/home/hazelnuss/workspace/node_modules/.pnpm/vite@4.1.4/node_modules/vite/dist/node/chunks/dep-ca21228b.js:52420:15)
```

### Reproduction

https://codesandbox.io/p/sandbox/goofy-https-bblb9u?welcome=true&file=%2FREADME.md

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by frenicohansen** [comment]
I just looked into the source code for the astro plugin. I am just wondering why is the _CSS reset_ injected by default in the configuration. It is mentioned in the README, that UnoCss doesn't do this by default.

> ### Style Resetting
> UnoCSS does not provide style resetting or preflight by default for maximum flexibility and does not populate your global CSS. If you use UnoCSS along with other CSS frameworks, they probably already do the resetting for you. If you use UnoCSS alone, you can use resetting libraries like [Normalize.css](https://necolas.github.io/normalize.css/).

**Comment by frenicohansen** [comment]
```
export default defineConfig({
  integrations: [
    UnoCss({
      injectReset: false,
      // ... custom config
    }),
  ],
});
```

That should solve the issue.

**Comment by antfu** [comment]
It's more like a pnpm hositing issue, `@unocss/reset` is already a dependency of `@unocss/astro`, which honestly, I think there isn't much for us to improve here.
