### ISSUE TITLE
@unocss/eslint-config doesn't work on pnpm monorepo with vscode?

### ISSUE THREAD

**Issue by Geddard** [unocss/unocss#2603]
### UnoCSS version

any

### Describe the bug

I'm trying to use the eslint plugin for unocss, [the older one](https://github.com/devunt/eslint-plugin-unocss) from  devunt doesn't have the options to configure linting for other attributes besides `className` so i was trying to use the tailwind one, but the latter doesn't pick up the `uno.config.ts` custom values.

I installed @unocss/eslint-config and tried following the [official instructions](https://unocss.dev/integrations/eslint) but when i open a file with unocss classes i get an error like this for ESlint output.

```
[Error - 12:38:47] An unexpected error occurred:
[Error - 12:38:47] Error: [@unocss/eslint-plugin] No config file found, create a `uno.config.ts` file in your project root and try again.
    at getGenerator (/---/uno-monorepo/node_modules/.pnpm/@unocss+eslint-plugin@0.51.12_eslint@8.40.0_typescript@5.0.4/node_modules/@unocss/eslint-plugin/dist/worker-sort.cjs:37:11)
    at async /---/uno-monorepo/node_modules/.pnpm/@unocss+eslint-plugin@0.51.12_eslint@8.40.0_typescript@5.0.4/node_modules/@unocss/eslint-plugin/dist/worker-sort.cjs:43:15
```

### Reproduction

I've uploaded a reproduction repo, these are the steps to reproduce:

[Repo link](https://github.com/Geddard/monorepo-unocss)

1) clone the repo
2) run `pnpm install`
3) open a `.tsx` file, `page.tsx` has unocss class applied or apply a class to a new file
4) observe the eslint output for vscode

Screenshot:

<img width="1388" alt="Screenshot 2023-05-10 at 12 48 25" src="https://github.com/unocss/unocss/assets/3460028/495146e3-4a38-47e0-b01c-c1e7eace22d8">

### System Info

- laptop: MacBook Air M1 13 inches
- OS: Ventura latest version
- IDE: VScode
- Package Manager: pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Geddard** [comment]
And btw, it would be awesome if the lint plugin would support `callees` like the tailwind one does, so we can have linting for `clsx` classes

**Comment by szluyu99** [comment]
I had the same problem

**Comment by Geddard** [comment]
> I had the same problem

had? you mean you fixed it somehow?

So far my only option has been to use the tailwind plugin, not easy to configure for Uno but i imanaged.

and anyway this eslint plugin fo Uno is quite lacking, besides not being able to handle `callees`, it doesn't work very well for duplicate classnames or attribufy order. So i think im going to stick with tailwinds plugin until a 1.0 version of this one i think

**Comment by Yorksh1re** [comment]
+1

**Comment by so1ve** [comment]
> my temporary solution is to create a "uno.config.ts" in the root directory and write the following content in it:
> 
> ```ts
> // for eslint;
> import { defineConfig } from 'unocss'
> 
> export default defineConfig({
>   configFile: './components/uno.config.ts',
> })
> ```
> 
> At least it stops throwing this error message `[@unocss/eslint-plugin] No config file found`.
> 
> You can refer to this project: [cherryful/unocss-ui](https://github.com/cherryful/unocss-ui)

That's a little bit complex - you can replace its content with:

```ts
// To make @unocss/eslint-plugin work
export { default } from "./packages/foo/uno.config";
```

**Comment by Bernankez** [comment]
> > my temporary solution is to create a "uno.config.ts" in the root directory and write the following content in it:
> > ```ts
> > // for eslint;
> > import { defineConfig } from 'unocss'
> > 
> > export default defineConfig({
> >   configFile: './components/uno.config.ts',
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > At least it stops throwing this error message `[@unocss/eslint-plugin] No config file found`.
> > You can refer to this project: [cherryful/unocss-ui](https://github.com/cherryful/unocss-ui)
> 
> That's a little bit complex - you can replace its content with:
> 
> ```ts
> // To make @unocss/eslint-plugin work
> export { default } from "./packages/foo/uno.config";
> ```

This also fix my unocss eslint auto fix👍

**Comment by nekomeowww** [comment]
> That's a little bit complex - you can replace its content with:
> 
> ```ts
> // To make @unocss/eslint-plugin work
> export { default } from "./packages/foo/uno.config";
> ```

What if I have multiple packages that holds their own `uno.config.ts`? Do I export them all with a spread syntax all at once in the root `uno.config.ts`?
Is that possible to configure the `@unocss/eslint-config` that consumes the similar config pattern for `unocss.root` that the unocss VSCode extension uses therefore we could have a stable behavior?

**Comment by Mikasa33** [comment]
Error: [@unocss/eslint-plugin] No config file found, create a `uno.config.ts` file in your project root and try again.

I used flat eslint config, but I don't know how to solve this problem.
If create `uno.config.ts` in the root directory, there will be two prompts...

```
- project
  - packages
    - package-a
      - uno.config.ts
  - eslint.config.js
  - uno.config.ts // Repeat prompt
```

```js
// project/eslint.config.js

import antfu from '@antfu/eslint-config'
import unocss from '@unocss/eslint-config/flat'

export default antfu(
  {},
  unocss,
)
```

<img width="856" alt="image" src="https://github.com/unocss/unocss/assets/29498153/e0ddd53a-4e19-4823-9aaf-8887cb2da813">

**Comment by itpropro** [comment]
@antfu do you think the idea from @nekomeowww of using the same setting already existent for the unocss vscode extension (`unocss.root`) for eslint to resolve the unocss config would be feasible?

**Comment by xsjcTony** [comment]
@antfu Sorry for the straightaway ping, but this is a critical issue for using this eslint plugin in monorepo project, as described above. This needs to be addressed as a priority from my perspective. Thanks.

**Comment by antfu** [comment]
I don't have the bandwidth to look into this right now. If someone could propose some solutions via PRs, it might help this to move faster.

**Comment by mizasobi** [comment]
Hi,

Another workaround is to create an UnoCSS ESLint config object for each package and add `settings.unocss.configPath` to it.  
This seems to work well for multiple packages with different UnoCSS configs.

Here is a minimal example using `@antfu/eslint-config`:

```js
// eslint.config.js

import { fileURLToPath } from 'node:url'
import antfu from '@antfu/eslint-config'
import unocss from '@unocss/eslint-config/flat'

export default antfu(
  {},
  {
    ...unocss,
    files: ['packages/your-package/**/*'],
    name: 'your-package/unocss',
    settings: {
      unocss: {
        configPath: fileURLToPath(new URL('./packages/package-1/uno.config.ts', import.meta.url)),
      },
    },
  },
  // Configs for other packages
)
```

Repository: [mizasobi/monorepo-for-unocss-with-eslint](https://github.com/mizasobi/monorepo-for-unocss-with-eslint)

Faced with the same problem, I dug into the code and found the UnoCSS config can be loaded from `configPath` instead of the CWD.  
[packages-integrations/eslint-plugin/src/worker.ts](github.com/unocss/unocss/blob/3107503eac1bcdec03c78e721fe98e4c85d07025/packages-integrations/eslint-plugin/src/worker.ts)

I got a hint on how to pass `configPath` from here:  
[packages-integrations/eslint-plugin/src/rules/order.test.ts](https://github.com/unocss/unocss/blob/c6adc2e45e84d254f0fb8d1a8c9101aca1eb8f29/packages-integrations/eslint-plugin/src/rules/order.test.ts)
