### ISSUE TITLE
0.52.0 broke Astro integration

### ISSUE THREAD

**Issue by Hrishikesh-K** [unocss/unocss#2646]
### UnoCSS version

0.52.0

### Describe the bug

Running `astro dev` in a project with UnoCSS v0.52.0 gives the error:

```
Failed to load url /uno.css?uno-with-astro-key (resolved id: /uno.css?uno-with-astro-key) in uno-astro. Does the file exist?
14:20:42 [vite] Error when evaluating SSR module uno-astro: failed to import "/uno.css?uno-with-astro-key"
|- Error: Failed to load url /uno.css?uno-with-astro-key (resolved id: /uno.css?uno-with-astro-key) in uno-astro. Does the file exist?
    at loadAndTransform (file://file:///home/projects/unocss-2646/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53428:21)

14:20:42 [vite] Error when evaluating SSR module astro:scripts/page-ssr.js: failed to import "uno-astro"
|- Error: Failed to load url /uno.css?uno-with-astro-key (resolved id: /uno.css?uno-with-astro-key) in uno-astro. Does the file exist?
    at loadAndTransform (file://file:///home/projects/unocss-2646/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53428:21)

14:20:42 [vite] Error when evaluating SSR module /home/projects/unocss-2646/src/pages/index.astro: failed to import "astro:scripts/page-ssr.js"
|- Error: Failed to load url /uno.css?uno-with-astro-key (resolved id: /uno.css?uno-with-astro-key) in uno-astro. Does the file exist?
    at loadAndTransform (file://file:///home/projects/unocss-2646/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53428:21)

 error   Could not import `/uno.css?uno-with-astro-key`.
  Hint:
    This is often caused by a typo in the import path. Please make sure the file exists.
  File:
    /home/projects/unocss-2646/file:/file:/home/projects/unocss-2646/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53428:21
  Stacktrace:
Error: Failed to load url /uno.css?uno-with-astro-key (resolved id: /uno.css?uno-with-astro-key) in uno-astro. Does the file exist?
    at loadAndTransform (file://file:///home/projects/unocss-2646/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53428:21)

 error   Could not import `/uno.css?uno-with-astro-key`.
  Hint:
    This is often caused by a typo in the import path. Please make sure the file exists.
  File:
    /home/projects/unocss-2646/file:/file:/home/projects/unocss-2646/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53428:21
  Stacktrace:
Error: Failed to load url /uno.css?uno-with-astro-key (resolved id: /uno.css?uno-with-astro-key) in uno-astro. Does the file exist?
    at loadAndTransform (file://file:///home/projects/unocss-2646/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53428:21)
 (x2)
```

v0.51.13 still works fine

### Reproduction

https://stackblitz.com/edit/unocss-2646

### System Info

Node 18.16.0
Chrome 113

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
https://github.com/unocss/unocss/pull/2593, cc @Dunqing if you have any idea on this

**Comment by Dunqing** [comment]
Sorry guy, I have found the cause and fixed it.
