### ISSUE TITLE
Async Preset loading

### ISSUE THREAD

**Issue by alexgrozav** [unocss/unocss#2720]
### Clear and concise description of the problem

While writing the Unocss Preset for Inkline, I've run into a blocker: the presets cannot be defined as async. When registering the preset, I need to be able to load Inkline's config file asynchronously in order to get the `theme` for the preset. Without it, I'm unable to finish and publish the preset.

If agreed upon, I can write a PR for it.

### Suggested solution

When loading `presets`, allow `theme` to  be defined as an async function returning a theme.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Read the `README.md` of using the package.
- [X] Already used the [Interactive Docs](https://uno.antfu.me).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Won't top-level await in the config file work for you?

**Comment by alexgrozav** [comment]
@antfu Unfortunately, `jiti` does not support top-level await (https://github.com/unjs/jiti/issues/72). When trying to use top-level await I get an error:

```ts
import { defineConfig } from "unocss";
import { createPreset } from "./src/preset";

const presetInkline = await createPreset();

export default defineConfig({
    presets: [presetInkline],
});
```

```bash
/Users/alexgrozav/Workspace/inkline/unocss/uno.config.ts:10
const presetInkline = await (0, _preset.createPreset)();var _default =
                      ^

ReferenceError: await is not defined
    at /Users/alexgrozav/Workspace/inkline/unocss/uno.config.ts:10:23
    at jiti (/Users/alexgrozav/Workspace/inkline/unocss/node_modules/jiti/dist/jiti.js:1:245784)
    at loadConfigFile (/Users/alexgrozav/Workspace/inkline/unocss/node_modules/unconfig/dist/index.cjs:155:11)
    at async Object.load (/Users/alexgrozav/Workspace/inkline/unocss/node_modules/unconfig/dist/index.cjs:82:24)
    at async Object.loadConfig (/Users/alexgrozav/Workspace/inkline/unocss/node_modules/@unocss/config/dist/index.cjs:50:18)
    at async Object.reloadConfig (/Users/alexgrozav/Workspace/inkline/unocss/node_modules/@unocss/vite/dist/index.cjs:74:20)
    at async FSWatcher.<anonymous> (/Users/alexgrozav/Workspace/inkline/unocss/node_modules/@unocss/vite/dist/index.cjs:820:9)
```

**Comment by minht11** [comment]
This is still an issue uno version 0.55.6.

**Comment by paschun** [comment]
Thanks @alexgrozav. Been running into jiti2 issues in vscode with async and the wrapper worked.
