### ISSUE TITLE
webpack error

### ISSUE THREAD

**Issue by kenixFog** [unocss/unocss#2782]
### UnoCSS version

0.53.1

### Describe the bug

**This problem can occur at any time when import css file or modify some configuration, it seems to be no trace**

```
TypeError: Cannot read properties of undefined (reading 'unocss:webpack')
    at Object.transform (E:\app\node_modules\.pnpm\unplugin@1.3.1\node_modules\unplugin\dist\webpack\loaders\transform.js:89:50)
    at LOADER_EXECUTION (E:\app\node_modules\.pnpm\loader-runner@4.3.0\node_modules\loader-runner\lib\LoaderRunner.js:132:14)
    at runSyncOrAsync (E:\app\node_modules\.pnpm\loader-runner@4.3.0\node_modules\loader-runner\lib\LoaderRunner.js:133:4)
    at iterateNormalLoaders (E:\app\node_modules\.pnpm\loader-runner@4.3.0\node_modules\loader-runner\lib\LoaderRunner.js:251:2)
    at E:\app\node_modules\.pnpm\loader-runner@4.3.0\node_modules\loader-runner\lib\LoaderRunner.js:224:4
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
```

### Reproduction

~

### System Info

win11
webpack 5.87.0
@unocss/webpack : 0.53.1,

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by luweiheng** [comment]
i has a same problem

**Comment by NNNaix** [comment]
would u use thread-loader in webpack?

**Comment by Xuwznln** [comment]
> would u use thread-loader in webpack? i have same question after useing thread-lodaer.

yes, the same problem occurred if using thread-loader

**Comment by BanShan-Alec** [comment]
> 您会在 webpack 中使用 thread-loader 吗？使用 thread-lodaer 后，我也有同样的问题。

相同问题，去除thread-loader可以
