### ISSUE TITLE
FetchError when loading web fonts

### ISSUE THREAD

**Issue by dwzkit** [unocss/unocss#2930]
### UnoCSS version

0.54.1

### Describe the bug

I'm encountering a FetchError when attempting to load web fonts in my project. The error occurs while the browser is loading, with the following message:
```
FetchError: fetch failed (https://fonts.googleapis.com/css2?family=DM+Sans&family=DM+Serif+Display&family=DM+Mono&display=swap)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetchRaw2 (file:///Users/dwz/code/study/tauri/qm-wendang/node_modules/.pnpm/ofetch@1.1.1/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:215:14)
    at async $fetchRaw2 (file:///Users/dwz/code/study/tauri/qm-wendang/node_modules/.pnpm/ofetch@1.1.1/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:215:14)
    at async $fetchRaw2 (file:///Users/dwz/code/study/tauri/qm-wendang/node_modules/.pnpm/ofetch@1.1.1/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:215:14)
    at async Module.$fetch2 (file:///Users/dwz/code/study/tauri/qm-wendang/node_modules/.pnpm/ofetch@1.1.1/node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)

```
<img width="1369" alt="image" src="https://github.com/unocss/unocss/assets/41875799/6be88229-1b63-48a0-9e73-5bf9bdf16418">

### Reproduction

1. Install and configure Vite and unocss in the project.
2. Start the Vite server using the usual command (e.g., npm run dev or yarn dev).
3. Open the web application in a browser.
4. Error occurs as the browser attempts to load the page. The page does not load as expected and instead displays the reported FetchError.

Before these steps, the application was running without any errors. The issue started appearing without any significant changes to the codebase or the environment.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
You can try to use this configration to skip fetch from you local. https://unocss.dev/presets/web-fonts#inlineimports
```diff
presetWebFonts: {
+ inlineimports: false,  
  ...
}
```

**Comment by perintery** [comment]
> ```diff
> inlineimports: false,  
> ```

inlineImports

**Comment by perintery** [comment]
I think this bug is related to the network. My company's computers have imposed many restrictions on the network, so this problem has occurred.
