### ISSUE TITLE
SyntaxError in taro

### ISSUE THREAD

**Issue by Wyatex** [unocss/unocss#3742]
### UnoCSS version

0.59.3

### Describe the bug

I'm having an error reported when I'm using unocss v0.59.3 in taro. And v0.58 works fine.

```
👽 Taro v3.6.26

D:\projects\taro\taro-vue3-starter\node_modules\.pnpm\@unocss+config@0.59.3\node_modules\@unocss\config\dist\index.mjs:1
import { resolve, dirname } from 'node:path';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.newLoader [as .mjs] (D:\projects\taro\taro-vue3-starter\node_modules\.pnpm\pirates@4.0.6\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (D:\projects\taro\taro-vue3-starter\node_modules\.pnpm\@unocss+webpack@0.59.3_webpack@5.91.0\node_modules\@unocss\webpack\dist\index.cjs:10:16)  
```

### Reproduction

https://github.com/Wyatex/taro-unocss-0.59

### System Info

Windows 11，Node v20.10.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I don't know taro enough, but doesn't it support ESM? And UnoCSS should be build-on for most of the cases, are you bundling it to the package?

**Comment by Wyatex** [comment]
I think there shouldn't be any bundling, as I just imported the plugin and passed it to Webpack.

```
// config/index.js
import UnoCSS from 'unocss/webpack';
export default defineConfig({
  mini: {
      webpackChain(chain) {
        chain.plugin('unocss').use(UnoCSS());
      },
  }
})
```

**Comment by antfu** [comment]
Try using `await import('unocss/webpack').then(r => r.default())` then

**Comment by Wyatex** [comment]
This method will also result in an error. I suspect it's because Taro doesn't support ESM, and the @unocss/config package doesn't provide a CJS bundle, which is ultimately causing this error.

**Comment by Wyatex** [comment]
https://github.com/NervJS/taro/issues/15487
