### ISSUE TITLE
unconfig dep jiti 1.21.1 cause error, 1.21.0 success

### ISSUE THREAD

**Issue by liuzw2579** [unocss/unocss#3868]
### UnoCSS version

0.60.4

### Describe the bug

error when starting dev server:
TypeError: (0 , _presetWind.presetWind) is not a function
    at /Volumes/WorkSpace/dimension/node_modules/.pnpm/@unocss+preset-uno@0.59.4/node_modules/@unocss/preset-uno/dist/index.mjs:69:43
    at /Volumes/WorkSpace/dimension/uno.config.ts:13:35
    at evalModule (/Volumes/WorkSpace/dimension/node_modules/.pnpm/jiti@1.21.1/node_modules/jiti/dist/jiti.js:1:247359)
    at jiti (/Volumes/WorkSpace/dimension/node_modules/.pnpm/jiti@1.21.1/node_modules/jiti/dist/jiti.js:1:245172)
    at loadConfigFile (file:///Volumes/WorkSpace/dimension/node_modules/.pnpm/unconfig@0.3.13/node_modules/unconfig/dist/index.mjs:177:13)
    at async Object.load (file:///Volumes/WorkSpace/dimension/node_modules/.pnpm/unconfig@0.3.13/node_modules/unconfig/dist/index.mjs:98:24)
    at async loadConfig (file:///Volumes/WorkSpace/dimension/node_modules/.pnpm/@unocss+config@0.59.4/node_modules/@unocss/config/dist/index.mjs:43:18)
    at async reloadConfig (file:///Volumes/WorkSpace/dimension/node_modules/.pnpm/@unocss+vite@0.59.4_rollup@4.18.0_vite@5.2.12_@types+node@20.14.1_sass@1.77.4_terser@5.31.0_/node_modules/@unocss/vite/dist/index.mjs:93:20)
    at async Object.updateRoot (file:///Volumes/WorkSpace/dimension/node_modules/.pnpm/@unocss+vite@0.59.4_rollup@4.18.0_vite@5.2.12_@types+node@20.14.1_sass@1.77.4_terser@5.31.0_/node_modules/@unocss/vite/dist/index.mjs:125:12)
    at async configResolved (file:///Volumes/WorkSpace/dimension/node_modules/.pnpm/@unocss+vite@0.59.4_rollup@4.18.0_vite@5.2.12_@types+node@20.14.1_sass@1.77.4_terser@5.31.0_/node_modules/@unocss/vite/dist/index.mjs:1029:7)
    at async Promise.all (index 4)
    at async resolveConfig (file:///Volumes/WorkSpace/dimension/node_modules/.pnpm/vite@5.2.12_@types+node@20.14.1_sass@1.77.4_terser@5.31.0/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:69639:5)
    at async _createServer (file:///Volumes/WorkSpace/dimension/node_modules/.pnpm/vite@5.2.12_@types+node@20.14.1_sass@1.77.4_terser@5.31.0/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:65857:20)
    at async CAC.<anonymous> (file:///Volumes/WorkSpace/dimension/node_modules/.pnpm/vite@5.2.12_@types+node@20.14.1_sass@1.77.4_terser@5.31.0/node_modules/vite/dist/node/cli.js:762:24)

### Reproduction

no

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Simon-He95** [comment]
#3869
