### ISSUE TITLE
VSCode extension and autocomplete don't work

### ISSUE THREAD

**Issue by vabatta** [unocss/unocss#3942]
### UnoCSS version

0.61.0

### Describe the bug

As soon as I'm editing a `class="<cursor>"` no autocomplete comes up from the UnoCSS VSCode extension as long as I'm not fully extending the default theme. 

I was able to track down the issue to https://github.com/unocss/unocss/blob/e3d3b2ed21f02c213351d2d2c1d46ae57cae808b/packages/autocomplete/src/parse.ts#L68 with the error log from my extension output to be:
```
🛠 Resolving config for /Users/vabatta/Projects/vite-project
🛠 New configuration loaded from
  - /Users/vabatta/Projects/vite-project/uno.config.ts
ℹ️ 1 presets, 714 rules, 0 shortcuts, 44 variants, 0 transformers loaded
🗂️ Enabled context: /Users/vabatta/Projects/vite-project
⚠️ Error on getting autocompletion items
Error: Invalid theme key duration
	at /Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95345:23
	at Array.reduce (<anonymous>)
	at /Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95343:33
	at Array.map (<anonymous>)
	at parts.push.type (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95342:37)
	at /Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95312:5
	at Array.forEach (<anonymous>)
	at handleRegexMatch (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95308:35)
	at handleNonGroup (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95336:5)
	at /Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95370:9
	at handleRegexMatch (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95316:5)
	at handleGroups (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95360:5)
	at parseAutocomplete (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95329:3)
	at getParsed (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95511:35)
	at /Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95601:73
	at Array.map (<anonymous>)
	at suggestFromPreset (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95601:22)
	at suggest (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95534:12)
	at async Object.suggestInFile (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95567:25)
	at async Object.provideCompletionItems (/Users/vabatta/.vscode/extensions/antfu.unocss-0.61.0/dist/index.js:95732:24)
	at async ve.provideCompletionItems (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:153:113339)
```

By adding the log line to my local extension code `log.appendLine('DEBUG ${...params}')` in the above snippet location, I can see that the function get passed the extended theme only rather than the whole theme:
```
DEBUG 
["$duration","duration"]
duration
{"fontFamily":{"title":"\"Neue Leiden\",ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\""},"colors":{"brandred":"#F17272","summer":"#3C84B9","autumn":"#E76E6E","winter":"#1E1E2F","spring":"#DDCA86"}}
duration
undefined // <-- this throws the error as duration is not in the object
```

I was able to reproduce the issue back to VSCode version `0.57.0`, before which I was unable to load with the latest UnoCSS package.

Potentially related issues:
- https://github.com/unocss/unocss/issues/3900
- https://github.com/unocss/unocss/issues/3883

### Reproduction

https://github.com/vabatta/unocss-bug-repro

There is also a devcontainer to have the same enviornment as I do. 

Config
```ts
import { defineConfig, presetMini } from 'unocss';

export default defineConfig({
	extendTheme: (theme) => ({
		// ...theme, // uncommenting this makes the extension work
		fontFamily: {
			title: `"Neue Leiden",${theme.fontFamily?.sans}`
		},
		colors: {
			brandred: "#F17272",
			// brandsand: "#EDE5C8",

			summer: "#3C84B9",
			autumn: "#E76E6E",
			winter: "#1E1E2F",
			spring: "#DDCA86",
		}
	}),
	presets: [
		presetMini(),
	]
})
```

### System Info

Version: 1.90.2
Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
Date: 2024-06-18T22:54:35.075Z (1 wk ago)
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.2.0

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by itsmnthn** [comment]
This is not fixed? i'm getting same error in version 66.0.0

**Comment by zyyv** [comment]
Sorry that this issue has not been updated for a long time, but the problem still exists

Update:
The reason for this problem is that in the preset dynamic rules, we configured the template for `autocomplete`, but the wrong theme key appeared in the configured meta information, resulting in a parsing error.

```ts
const dynamicRule = [
  /^foo-(.+)$/,
  function () { /.../ },
  { 
    autocomplete: 'foo-$errorThemeKey' // cause theme autocomplete parsed error
  }
]
```

There are a large number of rules in unocss, and almost all rules are configured for auto-completion. It is a huge and tedious task to carefully check the errors of a certain rule.

Solution:
Abandon throw error, skip the template parsing (or throw an error parsing log to record the wrong configuration template), and use normal work.

Thanks

**Comment by Albermonte** [comment]
> 
> Solution: Abandon throw error, skip the template parsing (or throw an error parsing log to record the wrong configuration template), and use normal work.
> 
> Thanks

Hi @zyyv , I just encountered this error in a newly created project using Nuxt
```
    "@antfu/eslint-config": "^5.0.0",
    "@unocss/eslint-plugin": "^66.3.3",
    "@unocss/nuxt": "^66.3.3",
    "@unocss/preset-wind4": "^66.3.3",
    "eslint": "^9.31.0",
    "nimiq-css": "1.0.0-beta.66",
    "unocss": "^66.3.3",
    "unocss-preset-onmax": "1.0.0-beta.37"
```
Extension version: `66.4.1`

I don't quite understand your "solution", can you explain a bit more how to apply this patch/fix?

Thank you

**Comment by zyyv** [comment]
@Albermonte Can you provide a minimal reproduction?

**Comment by Albermonte** [comment]
Minimal reproduction: https://github.com/Albermonte/unocss-issue-3942
Preset causing this issue: https://github.com/onmax/unocss-preset-onmax
@zyyv @onmax
