### ISSUE TITLE
Svelte Scoped: --at-apply errors in Svelte 5

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [unocss/unocss#3956]
### UnoCSS version

0.61.0

### Describe the bug

Not too sure what causes this but it seems like using `--at-apply` gives an error in Svelte 5:

```
[plugin:vite-plugin-svelte] src/routes/+page.svelte:55:149 Declaration cannot be empty
src/routes/+page.svelte:55:149
CompileError: Declaration cannot be empty
    at new InternalCompileError (file:///home/projects/unocss-unocss-z8yald/node_modules/svelte/src/compiler/errors.js:188:3)
    at e (file:///home/projects/unocss-unocss-z8yald/node_modules/svelte/src/compiler/errors.js:225:8)
    at Module.css_empty_declaration (file:///home/projects/unocss-unocss-z8yald/node_modules/svelte/src/compiler/errors.js:620:2)
    at read_declaration (file:///home/projects/unocss-unocss-z8yald/node_modules/svelte/src/compiler/phases/1-parse/read/style.js:498:5)
    at read_block_item (file:///home/projects/unocss-unocss-z8yald/node_modules/svelte/src/compiler/phases/1-parse/read/style.js:479:44)
    at read_block (file:///home/projects/unocss-unocss-z8yald/node_modules/svelte/src/compiler/phases/1-parse/read/style.js:447:18)
    at read_rule (file:///home/projects/unocss-unocss-z8yald/node_modules/svelte/src/compiler/phases/1-parse/read/style.js:132:10)
    at read_body (file:///home/projects/unocss-unocss-z8yald/node_modules/svelte/src/compiler/phases/1-parse/read/style.js:82:18)
    at Module.read_style (file:///home/projects/unocss-unocss-z8yald/node_modules/svelte/src/compiler/phases/1-parse/read/style.js:43:19)
    at element (file:///home/projects/unocss-unocss-z8yald/node_modules/svelte/sr
```

`@apply` still works fine.

### Reproduction

https://stackblitz.com/edit/unocss-unocss-z8yald?file=src%2Froutes%2F%2Bpage.svelte

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jacob-8** [comment]
My initial thought is that something in Svelte 5 may have changed the order in which the preprocessors run. I would start by using the Vite Plugin Inspector to debug if someone else gets to this before me.

**Comment by fehnomenal** [comment]
I found omitting the semicolon or adding anything, even an empty comment, after the `--at-apply: flex;` fixes the issue if there is any whitespace involved.
So all of the following work:
```css
:global(body) {
  --at-apply: flex
}
```
```css
:global(body) {
  --at-apply: flex; /**/
}
```
```css
:global(body) {
  --at-apply: flex;/* */
}
```
```css
:global(body) {
  --at-apply: flex;
  /* */
}
```

While this does not work:
```css
:global(body) {
  --at-apply: flex;/**/
}
```

**Comment by fehnomenal** [comment]
should be fixed by #4795

**Comment by henrikvilhelmberglund** [comment]
Thanks for the fix.

If you include fixes #issuenumberhere in the PR description body it will auto close when merged.
