### ISSUE TITLE
Playground does not start in cloned unocss repo

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [unocss/unocss#4046]
### UnoCSS version

0.61.9

### Describe the bug

It seems like I've got a shallow clone because I don't have tags.

```
$ git describe --tags
fatal: No names found, cannot describe anything.
```

This makes the playground error when starting because of the recent playground PR. I can understand the error but I'm not sure if the playground is supposed to work or not in a shallow copy. Maybe it could work but not allow for switching playground versions?

Log from trying to start the playground:

```
$ nr play

> @unocss/monorepo@0.61.9 play C:\Github\unocss
> npm -C playground run dev


> playground@0.61.9 dev
> vite --open

failed to load config from C:\Github\unocss\playground\vite.config.ts
error when starting dev server:
Error: fatal: No names found, cannot describe anything.

    at Object.action (file:///C:/Github/unocss/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/dist/esm/index.js:4463:25) 
    at PluginStore.exec (file:///C:/Github/unocss/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/dist/esm/index.js:4502:25)
    at file:///C:/Github/unocss/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/dist/esm/index.js:1369:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (file:///C:/Github/unocss/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/dist/esm/index.js:1367:16)
    at GitExecutorChain.<anonymous> (file:///C:/Github/unocss/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/dist/esm/index.js:1351:44)
    at Generator.next (<anonymous>)
    at fulfilled (file:///C:/Github/unocss/node_modules/.pnpm/simple-git@3.25.0/node_modules/simple-git/dist/esm/index.js:45:24)       
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
 ELIFECYCLE  Command failed with exit code 1.
 
```

### Reproduction

1. Clone unocss repo
2. In cloned repo `ni && nr build && nr play` (or `nr stub` instead of build)

If the above works:
1. Clone unocss repo, making sure it's a shallow clone
2. In cloned repo `ni && nr build && nr play` (or `nr stub` instead of build)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
you should run `nr build` or `nr stub` before starting playground

**Comment by antfu** [comment]
We could improve the developer setup in the contribution guide for this

**Comment by henrikvilhelmberglund** [comment]
Fixed by (in my case)
```
git fetch --tags upstream
git push -f --tags origin main
```
