### ISSUE TITLE
[@unocss/postcss] "Unknown word" error for className binding

### ISSUE THREAD

**Issue by tony19** [unocss/unocss#4073]
### UnoCSS version

0.62.1

### Describe the bug

The build fails if using `@unocss/postcss` in a React project that has a `className` binding (shown below). The failure still occurs even if that line is commented out.

```tsx
import { ReactNode } from 'react'

export default function Button({ children }: { children: ReactNode }) {
  const bgColor = 'blue'           // 👇 causes "Unknown word" error
  return <button className={`bg-[${bgColor}]`}>{children}</button>
}
```

Error:

```
2:11:31 AM [vite] Internal server error: [postcss] /__uno.css:5:42: Unknown word
  Plugin: vite:css
  File: /__uno.css:5:41
  3  |  /* layer: default */
  4  |  .bg-\[\'\ \+\ bgColor\ \+\ \'\]{background-color:' + bgColor + ' /* ' + bgColor + ' */;}
  5  |  .bg-\[\$\{bgColor\}\]{background-color:${bgColor} /* ${bgColor} */;}__uno_hash_70e0f6{--:'';}
     |                                           ^
      at Input.error (/home/projects/unocss-postcss-bug/node_modules/postcss/lib/input.js:106:16)
      at Parser.unknownWord (/home/projects/unocss-postcss-bug/node_modules/postcss/lib/parser.js:593:22)
      at Parser.other (/home/projects/unocss-postcss-bug/node_modules/postcss/lib/parser.js:435:12)
      at Parser.parse (/home/projects/unocss-postcss-bug/node_modules/postcss/lib/parser.js:470:16)
      at parse (/home/projects/unocss-postcss-bug/node_modules/postcss/lib/parse.js:11:12)
      at new LazyResult (/home/projects/unocss-postcss-bug/node_modules/postcss/lib/lazy-result.js:133:16)
      at Processor.process (/home/projects/unocss-postcss-bug/node_modules/postcss/lib/processor.js:53:14)
      at compileCSS (file:///home/projects/unocss-postcss-bug/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:36886:59)
      at async TransformPluginContext.transform (file:///home/projects/unocss-postcss-bug/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:36180:11)
      at async PluginContainer.transform (file:///home/projects/unocss-postcss-bug/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:49023:18)
```

Workaround: use string concatenation

```tsx
import { ReactNode } from 'react'

export default function Button({ children }: { children: ReactNode }) {
  const bgColor = 'blue'
  return <button className={'bg-[' + bgColor + ']'}>{children}</button>
}
```

This bug does not impact v0.60.4.

### Reproduction

https://stackblitz.com/edit/unocss-postcss-bug?file=src/Button.tsx

### System Info

System: macOS Sonoma, M1 Max
Browser: Arc 1.55
Node: 20.15.1 

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by s3xysteak** [comment]
Unocss relies on static analysis to know what classes should be generated, so you should use: 
```js
isRed ? `bg-red` : `bg-blue`
/**
 * .bg-red {}
 * .bg-blue {}
 */
```
instead of :
```js
`bg-${isRed ? 'red' : 'blue'}` 
// For compiler, Who knows what the var behind `bg-` could be?
```

**Comment by tony19** [comment]
Why wasn't this a problem in v0.60.4?

**Comment by s3xysteak** [comment]
Tried in your repro, in v0.60.4:
```json
{
    "unocss": "^0.60.4",
    "@unocss/postcss": "^0.60.4",
    "@unocss/preset-wind": "^0.60.4",
}
```
It just did not throw a error, the style still not work. 

This will work both in v0.60.4 and latest version:
```js
  const bgColor = 'bg-blue';
  return <button className={bgColor}>{children}</button>;
```

**Comment by Simon-He95** [comment]
> Why wasn't this a problem in v0.60.4?

Because the previous parseToken processing was incomplete, it may not have completely processed the content in your class. In any case, this approach is problematic if you don't use the uno [runtime](https://unocss.dev/integrations/runtime#bundler-usage) method.
