### ISSUE TITLE
vscode extension not work with `@iconify/tools`

### ISSUE THREAD

**Issue by zcf0508** [unocss/unocss#4200]
### UnoCSS version

0.63.4

### Describe the bug

Vscode extension highlight class name not works fine with custom icon set with `@iconify/tools`.

![work fine](https://github.com/user-attachments/assets/30cbdb14-7aa9-44c7-9cf8-773c066d77c8)

![not work with custom icon set](https://github.com/user-attachments/assets/0b4023c4-474e-4e0b-9eea-5653908755b4)

And I noticed this error in console tab.

![error](https://github.com/user-attachments/assets/a11a5c93-7884-44d1-9c06-fce1a47d1c67)

### Reproduction

https://github.com/zcf0508/unocss-vscode-not-work-with-iconify-tools

### System Info

  System:
    OS: macOS 14.2.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 727.07 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.version-fox/temp/1728835200-68847/nodejs/bin/node
    npm: 8.19.3 - ~/.version-fox/temp/1728835200-68847/nodejs/bin/npm
    pnpm: 8.15.8 - ~/.version-fox/temp/1728835200-68847/nodejs/bin/pnpm
    bun: 1.1.25 - ~/.bun/bin/bun
  Browsers:
    Chrome: 129.0.6668.91
    Edge: 129.0.2792.89
    Safari: 17.2.1

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zcf0508** [comment]
https://github.com/unocss/unocss/issues/4218

**Comment by zumm** [comment]
I'm facing similar problem. My config:
```ts
function loadCustomIconSet(path: string) {
  const iconSet = importDirectorySync(path, {
    prefix: 'svg',
  })

  const whiteColor = stringToColor('white')!
  iconSet.forEachSync((name) => {
    const svg = iconSet.toSVG(name)!

    parseColors(svg, {
      defaultColor: 'currentColor',
      callback: (attributes, colorString, color) => {
        if (color && compareColors(color, whiteColor)) {
          return 'currentColor'
        }

        switch (color?.type) {
          case 'none':
          case 'current':
            return color
        }

        throw new Error(`Unexpected color "${colorString}" in attribute ${attributes}`)
      },
    })

    runSVGO(svg)
    deOptimisePaths(svg)
    iconSet.fromSVG(name, svg)
  })

  return () => iconSet.export()
}

export default defineConfig({
  presets: [
    presetIcons({
      collections: {
        custom: loadCustomIconSet('assets/icons'),
      },
    }),
  ],
})
```

Seems like extension uses wrong working dir. Logs:
```text
⚪️ UnoCSS for VS Code v65.4.3

📂 roots search mode.

-----------
🛠 Resolving config for c:\Users\zumm\cloud\private\projects\mobilitymag
⚠️ Error on loading config. Config directory: c:\Users\zumm\cloud\private\projects\mobilitymag
Error: ENOENT: no such file or directory, scandir 'C:\Program Files\Microsoft VS Code\assets\icons'
    at readdirSync (node:fs:1508:26)
    at t.readdirSync (node:electron/js2c/node_init:2:13703)
    at scan (C:/Users/zumm/cloud/private/projects/mobilitymag/node_modules/.pnpm/@iconify+tools@4.1.1/node_modules/@iconify/tools/lib/misc/scan.mjs:71:39)
    at scanDirectorySync (C:/Users/zumm/cloud/private/projects/mobilitymag/node_modules/.pnpm/@iconify+tools@4.1.1/node_modules/@iconify/tools/lib/misc/scan.mjs:102:3)
    at importDirectorySync (C:/Users/zumm/cloud/private/projects/mobilitymag/node_modules/.pnpm/@iconify+tools@4.1.1/node_modules/@iconify/tools/lib/import/directory.mjs:125:45)
    at loadCustomIconSet (c:/Users/zumm/cloud/private/projects/mobilitymag/uno.config.ts:10:50)
    at c:/Users/zumm/cloud/private/projects/mobilitymag/uno.config.ts:80:15
    at Function.import (c:\Users\zumm\.vscode\extensions\antfu.unocss-65.4.3\dist\jiti-37OA45AY.cjs:2964:25)
    at Object.loader (c:\Users\zumm\.vscode\extensions\antfu.unocss-65.4.3\dist\jiti-37OA45AY.cjs:31407:15)
    at Object.importx (c:\Users\zumm\.vscode\extensions\antfu.unocss-65.4.3\dist\dist-HLCVOOKS.cjs:326:19)
    at c:\Users\zumm\.vscode\extensions\antfu.unocss-65.4.3\dist\index.cjs:36193:21
    at loadConfigFile (c:\Users\zumm\.vscode\extensions\antfu.unocss-65.4.3\dist\index.cjs:36191:18)
    at Object.load (c:\Users\zumm\.vscode\extensions\antfu.unocss-65.4.3\dist\index.cjs:36123:24)
    at loadConfig (c:\Users\zumm\.vscode\extensions\antfu.unocss-65.4.3\dist\index.cjs:36276:18)
    at c:\Users\zumm\.vscode\extensions\antfu.unocss-65.4.3\dist\index.cjs:36290:22
    at reloadConfig (c:\Users\zumm\.vscode\extensions\antfu.unocss-65.4.3\dist\index.cjs:36350:20)
🗂️ Enabled context: [none]
```

**Comment by 0xEFEF** [comment]
Using an absolute path can temporarily resolve this issue.
```diff
+ import { join } from 'node:path';

- importDirectorySync('src/assets/icons', { prefix: 'svg' })
+ importDirectorySync(join(__dirname, 'src/assets/icons'), { prefix: 'svg' })
```

**Comment by zcf0508** [comment]
https://github.com/unocss/unocss/issues/4218#issuecomment-2540406680
