### ISSUE TITLE
Running `nr play` failed, after cloning the unocss repository

### ISSUE THREAD

**Issue by mutuguangda** [unocss/unocss#4264]
### UnoCSS version

main

### Describe the bug

I cloned the unocss repository and I refer to the contributor documentation:
1. nci
2. nr stub
3. Running 'nr play' to report an error:
```
failed to load config from D:\projects\unocss\playground\vite.config.ts
error when starting dev server:
TypeError: Cannot redefine property: handler
    at Function.defineProperty (<anonymous>)
    at D:/projects/unocss/packages/preset-mini/src/_utils/index.ts:4:220
    at Array.forEach (<anonymous>)
    at D:/projects/unocss/packages/preset-mini/src/_utils/index.ts:4:72
    at evalModule (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:247313)
    at jiti (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:245241)
    at D:/projects/unocss/packages/preset-mini/src/utils.ts:1:151
    at evalModule (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:247313)
    at jiti (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:245241)
    at D:/projects/unocss/packages/inspector/src/analyzer.ts:3:14
    at evalModule (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:247313)
    at jiti (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:245241)
    at D:/projects/unocss/packages/inspector/src/index.ts:10:17
    at evalModule (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:247313)
    at jiti (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:245241)
    at D:/projects/unocss/packages/inspector/dist/index.mjs:10:3
    at evalModule (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:247313)
    at jiti (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:245241)
    at D:/projects/unocss/packages/vite/src/index.ts:5:41
    at evalModule (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:247313)
    at jiti (D:\projects\unocss\node_modules\.pnpm\jiti@1.21.6\node_modules\jiti\dist\jiti.js:1:245241)
    at file:///D:/projects/unocss/packages/vite/dist/index.mjs:10:3
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadConfigFromBundledFile (file:///D:/projects/unocss/node_modules/.pnpm/vite@5.4.8_@types+node@22.7.4_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:66634:15)
    at async loadConfigFromFile (file:///D:/projects/unocss/node_modules/.pnpm/vite@5.4.8_@types+node@22.7.4_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:66475:24)
    at async resolveConfig (file:///D:/projects/unocss/node_modules/.pnpm/vite@5.4.8_@types+node@22.7.4_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:66083:24)
    at async _createServer (file:///D:/projects/unocss/node_modules/.pnpm/vite@5.4.8_@types+node@22.7.4_terser@5.34.1/node_modules/vite/dist/node/chunks/dep-CDnG8rE7.js:62701:18)
    at async CAC. <anonymous> (file:///D:/projects/unocss/node_modules/.pnpm/vite@5.4.8_@types+node@22.7.4_terser@5.34.1/node_modules/vite/dist/node/cli.js:735:20)
 ELIFECYCLE  Command failed with exit code 1.
```

### Reproduction

Maybe I can provide some of my information here：
```
  System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
    Memory: 4.18 GB / 15.80 GB
  Binaries:
    Node: 18.20.4 - ~\AppData\Local\fnm_multishells\5020_1731575454703\node.EXE
    npm: 10.7.0 - ~\AppData\Local\fnm_multishells\5020_1731575454703\npm.CMD   
    pnpm: 8.9.2 - D:\projects\unocss\node_modules\.bin\pnpm.CMD
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zyyv** [comment]
Try to run `nr build` first.
