### ISSUE TITLE
uniapp 项目使用unocss，安装了vscode插件，在vscode没有提示，但样式都是生效的。

### ISSUE THREAD

**Issue by dxhuii** [unocss/unocss#650]
vite.config.ts 配置
```ts
import { defineConfig } from 'vite'
import path from 'path'
import uni from '@dcloudio/vite-plugin-uni'
import { presetUno, presetAttributify } from 'unocss'
import Unocss from 'unocss/vite'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni(),
    Unocss({
      presets: [presetAttributify(), presetUno()]
    })
  ],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src')
    }
  }
})
```
使用路径 src/pages/index/index.vue
```ts
<template>
  <view class="flex flex-col justify-center items-center">
    <image class="w-40 h-40 mt-20 mx-auto mb-10" src="/static/logo.png" />
    <view class="flex justify-center">
      <text class="text-xl text-gray-500"> {{ title }} </text>
    </view>
  </view>
</template>

<script setup lang="ts">
import { ref, watchEffect } from 'vue'
const title = ref('Hello')
</script>

<style></style>
```

**Comment by dxhuii** [comment]
用了一个临时解决办法，就是装tailwindcss的vscode插件，弄一个tailwind.config.js的配置，在vscode里面就能正提示了。

<img width="854" alt="image" src="https://user-images.githubusercontent.com/2328917/155677028-a5a098a7-6d61-4158-a6b4-d2522c6ca8f8.png">

**Comment by hannoeru** [comment]
Duplicated of https://github.com/unocss/unocss/issues/320

**Comment by yiescc** [comment]
安装了unocss插件，但是并没有出现提示及自动补全

**Comment by dxhuii** [comment]
> 安装了unocss插件，但是并没有出现提示及自动补全

https://github.com/unocss/unocss/issues/650#issuecomment-1050618853  按这里弄一下，

**Comment by nyrf** [comment]
请问你们怎么用 在uniapp上的，我这用hbuilder一运行就报错, nodejs已经17了
```
15:10:42.231 failed to load config from /Users/nyrf/Codes/vue/uniapps/demos/css_demo/vite.config.js
15:10:42.241 error when starting dev server:
15:10:42.251 /Users/nyrf/Codes/vue/uniapps/demos/css_demo/node_modules/unconfig/dist/index.cjs:69
15:10:42.263       const flatTargets = utils.toArray(source?.files || []).flatMap((file) => !extensions.length ? [file] : extensions.map((i) => i ? `${file}.${i}` : file));
15:10:42.280                                                ^
15:10:42.298 SyntaxError: Unexpected token '.'
15:10:42.314     at wrapSafe (internal/modules/cjs/loader.js:915:16)
15:10:42.331     at Module._compile (internal/modules/cjs/loader.js:963:27)
15:10:42.347     at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
15:10:42.364     at Object.require.extensions.<computed> [as .js] (/Users/nyrf/Codes/vue/uniapps/demos/css_demo/node_modules/vite/dist/node/chunks/dep-9c153816.js:71419:13)
15:10:42.380     at Module.load (internal/modules/cjs/loader.js:863:32)
15:10:42.398     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
15:10:42.413     at Module.require (internal/modules/cjs/loader.js:887:19)
15:10:42.431     at require (internal/modules/cjs/helpers.js:74:18)
15:10:42.447     at Object.<anonymous> (/Users/nyrf/Codes/vue/uniapps/demos/css_demo/node_modules/@unocss/config/dist/index.cjs:7:18)
15:10:42.464     at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**Comment by weiquanju** [comment]
> 用了一个临时解决办法，就是装tailwindcss的vscode插件，弄一个tailwind.config.js的配置，在vscode里面就能正提示了。
> 
> <img alt="image" width="854" src="https://user-images.githubusercontent.com/2328917/155677028-a5a098a7-6d61-4158-a6b4-d2522c6ca8f8.png">

魔法打败魔法 哈哈

**Comment by weiquanju** [comment]
https://github.com/unocss/unocss/issues/650#issuecomment-1050618853 魔法打败魔法 哈哈 🤣
